export const GET_PEOPLECONTROL_REQUEST =
  '@peoplecontrol/GET_PEOPLECONTROL_REQUEST';
export const GET_PEOPLECONTROL_SUCCESS =
  '@peoplecontrol/GET_PEOPLECONTROL_SUCCESS';
export const ADD_PEOPLECONTROL_REQUEST =
  '@peoplecontrol/ADD_PEOPLECONTROL_REQUEST';
export const ADD_PEOPLECONTROL_SUCCESS =
  '@peoplecontrol/ADD_PEOPLECONTROL_SUCCESS';
export const UPDATE_PEOPLECONTROL_REQUEST =
  '@peoplecontrol/UPDATE_PEOPLECONTROL_REQUEST';
export const UPDATE_PEOPLECONTROL_SUCCESS =
  '@peoplecontrol/UPDATE_PEOPLECONTROL_SUCCESS';
export const DELETE_PEOPLECONTROL_REQUEST =
  '@peoplecontrol/DELETE_PEOPLECONTROL_REQUEST';
export const DELETE_PEOPLECONTROL_SUCCESS =
  '@peoplecontrol/DELETE_PEOPLECONTROL_SUCCESS';
export const CLEAR_PEOPLECONTROL = '@peoplecontrol/CLEAR_PEOPLECONTROL';
export const PEOPLECONTROL_ERROR = '@peoplecontrol/PEOPLECONTROL_ERROR';

export const SET_CURRENT_PEOPLECONTROL_REQUEST =
  '@currentpeoplecontrol/SET_CURRENT_PEOPLECONTROL_REQUEST';
export const SET_CURRENT_PEOPLECONTROL_SUCCESS =
  '@currentpeoplecontrol/SET_CURRENT_PEOPLECONTROL_SUCCESS';
