export const GET_PEOPLETYPES_REQUEST = '@peopletypes/GET_PEOPLETYPES_REQUEST';
export const GET_PEOPLETYPES_SUCCESS = '@peopletypes/GET_PEOPLETYPES_SUCCESS';
export const ADD_PEOPLETYPES_REQUEST = '@peopletypes/ADD_PEOPLETYPES_REQUEST';
export const ADD_PEOPLETYPES_SUCCESS = '@peopletypes/ADD_PEOPLETYPES_SUCCESS';
export const DELETE_PEOPLETYPES_REQUEST =
  '@peopletypes/DELETE_PEOPLETYPES_REQUEST';
export const DELETE_PEOPLETYPES_SUCCESS =
  '@peopletypes/DELETE_PEOPLETYPES_SUCCESS';
