export const GET_DWELLERS_REQUEST = '@dwellers/GET_DWELLERS_REQUEST';
export const GET_DWELLERS_SUCCESS = '@dwellers/GET_DWELLERS_SUCCESS';
export const ADD_DWELLERS_REQUEST = '@dwellers/ADD_DWELLERS_REQUEST';
export const ADD_DWELLERS_SUCCESS = '@dwellers/ADD_DWELLERS_SUCCESS';
export const UPDATE_DWELLERS_REQUEST = '@dwellers/UPDATE_DWELLERS_REQUEST';
export const UPDATE_DWELLERS_SUCCESS = '@dwellers/UPDATE_DWELLERS_SUCCESS';

export const DELETE_DWELLERS_REQUEST = '@dwellers/DELETE_DWELLERS_REQUEST';
export const DELETE_DWELLERS_SUCCESS = '@dwellers/DELETE_DWELLERS_SUCCESS';
export const SET_CURRENT_DWELLERS_REQUEST =
  '@currentdweller/SET_CURRENT_DWELLERS_REQUEST';
export const SET_CURRENT_DWELLERS_SUCCESS =
  '@currentdweller/SET_CURRENT_DWELLERS_SUCCESS';
