export const GET_PEOPLES_REQUEST = '@peoples/GET_PEOPLES_REQUEST';
export const GET_PEOPLES_SUCCESS = '@peoples/GET_PEOPLES_SUCCESS';
export const ADD_PEOPLES_REQUEST = '@peoples/ADD_PEOPLES_REQUEST';
export const ADD_PEOPLES_SUCCESS = '@peoples/ADD_PEOPLES_SUCCESS';
export const UPDATE_PEOPLES_REQUEST = '@peoples/UPDATE_PEOPLES_REQUEST';
export const UPDATE_PEOPLES_SUCCESS = '@peoples/UPDATE_PEOPLES_SUCCESS';
export const DELETE_PEOPLES_REQUEST = '@peoples/DELETE_PEOPLES_REQUEST';
export const DELETE_PEOPLES_SUCCESS = '@peoples/DELETE_PEOPLES_SUCCESS';
export const CLEAR_PEOPLES = '@peoples/CLEAR_PEOPLES';
export const PEOPLES_ERROR = '@peoples/PEOPLES_ERROR';

export const SET_CURRENT_PEOPLE_REQUEST =
  '@currentpeople/SET_CURRENT_PEOPLE_REQUEST';
export const SET_CURRENT_PEOPLE_SUCCESS =
  '@currentpeople/SET_CURRENT_PEOPLE_SUCCESS';
